### ISSUE TITLE
虫洞功能测试

### ISSUE THREAD

**Issue by sxlwar** [darwinia-network/wormhole-ui#1]
## 网络选择

- 应用启动时，依次从 url > localStorage中查询可用的网络信息 。

- 如果有设置的 from 网络，会自动连接网络

> test net 和 main net 不能互发， 所以当网络不在同一环境下时只设置发送方，接收方的网络被忽略，由用户重新选择。

- 当发送方或接收方的网络发生变化时，会触发对侧网络的检验，只有通过校验的网络才能出现在选择列表中。

> 两侧不能选择同一网络

> 主网和测试网不能互通，当选择的网络是 主网or测试网 时，另一侧只能显示 主网or测试 网络，如果已选择 测试 or主网 网络，将重置。（实际可能不会发生，除非配置出现错误）

> 选择 from 时，to 侧的网络必须是满足 from -> to，同理，选择 to 时 from 侧的网络也必须满足 from -> to

> 选择 from 后，网络状态会出现几种不同的状态

> 已连接所选网络，图标绿色

> 已连接网络，但和所选的网络不一致，黄色（用户可选择切换或仍然停留在此网络）

> 网络未连接，红色

> 当无法完成从 from -> to 的操作时网络图标消失

> 当 from 和 to 选择时，如果无法完成 from -> to 的操作，中间箭头消失，以虚线连接。

- 网络间的关系用图结构表示，使用邻接表建立图之间的关系，在图关系中包含节点状态信息

如果顶点处于 pending 状态，顶点会出现在列表中，但无法触发网络连接

- 在开发环境中默认所有的网络都可用，在生产环境中测试网默认不显示，用户可以通过右上角下拉菜单中的 enable test net选择开启会隐藏。

## 表单

- 通用字段检查

> 非空检查、地址格式检查

> 数值范围（转账金额最大值为，余额 - 手续费）

- E2D

> 授权金额，转账金额超过授权金额

- D2E

> ring 或 kton 至少选择一个

> ring 余额 < 手续费 禁用，ring 余额 + 手续费  <  转账ring 数量  禁用

----

e2d 授权 ring

![e2d-authorize-ring](https://user-images.githubusercontent.com/20088392/127946894-23a789df-279d-4782-8fd0-10dc7f5a8107.gif)

e2d ring

![e2d-ring](https://user-images.githubusercontent.com/20088392/127946927-d4c44ba1-cd68-4c9f-a668-4dc7570d7569.gif)

e2d kton

![e2d-kton](https://user-images.githubusercontent.com/20088392/127946941-0ea3c8bf-6bba-4acb-8213-059341ec22e9.gif)

d2e 

![d2e](https://user-images.githubusercontent.com/20088392/127946961-ef2329c9-8034-44af-b28d-a87da2a958c1.gif)

**Comment by 1022ranji** [comment]
有个疑问，发送网络与接收网络的“重新选择”按钮有没有可能不需要设置呢？例如规定接收网络是根据发送网络而定的，这样前面的发送网络可以列出所有的网络列表，选择其中一个，后面的接收网络就会展示该发送网络下的相应网络。因为这个步骤只是选择，还没有连接钱包，也就是发送网络可以随意切换。
![image](https://user-images.githubusercontent.com/80877629/127981502-5205bf0a-fb3b-4e0f-9e28-c768efe37c39.png)

**Comment by sxlwar** [comment]
肯定可以，而且实现也比现在的简单，但灵活性不好

场景：A->B 发了个收 token 的 link， 这个 link 上就可能只有收款网络 ，因为 A 可能也不关心 B 会从哪个网络给他转账。

这个时候就需要从到达判断可用的出发

**Comment by AlexChien** [comment]
打开页面，默认选中了网络，并弹出metamask进行连接，比较正常。

但是，如果在源链下拉框中选择了“重新选择”，画面则变空白（黑色背景）

**Comment by AlexChien** [comment]
中文语言下，接受账号下方的tip描述是英文的

**Comment by AlexChien** [comment]
接受账号输入的地址如果不是目标地址，在我的测试中，目标链选择的是达尔文，但是输入的地址是 substrate 格式地址，在点击“发起跨链”时，页面上没有错误提示，只在console中抛出错误，抱怨prefix不是42.

**Comment by 1022ranji** [comment]
场景：A->B 发了个收 token 的 link， 当 link 中只有收款网络时，反向判断可用的发送网络。
但是在转账完成后，默认还是这个状态，这时想要再次从C > D 进行转账的话，由于接收网络已经确定了，所以发送网络即使想要“重新选择”也无法进行，必须先在接收网络处点击“重新选择”，然后再回到发送网络，之后再选择接收网络，这样操作起来步骤比较繁琐。

**Comment by AlexChien** [comment]
发起跨链后，页面阻断，出现右上角有个小的notification，Queueing...。知道交易确认后，弹出一个dialog，显示交易的起源地址、目的地地址等信息，并注明交易完成后。

如果之前的提示框是阻断的，那何不直接弹出dialog进行阻断，在窗口中展示该笔跨链的详情，以及交易状态呢？

**Comment by AlexChien** [comment]
这笔交易在发出后，无法进行查看进度及最终状态。估计功能尚未完成。

**Comment by AlexChien** [comment]
Darwinia -> Ethereum 不可以的么？

**Comment by 1022ranji** [comment]
miannet这种叫法后面应该要统一一下，
达尔文主网：Darwinia Network
Crab网络：Darwinia Crab Network
测试网：Pangolin Text Network
DVM： Darwinia Smart App

**Comment by xiaoch05** [comment]
> Darwinia -> Ethereum 不可以的么？

必须要先把目标网络重新选择，发送网络才能显示Darwinia，感觉这个地方这样设计不太好

**Comment by AlexChien** [comment]
源链选择更换后，连接新链的钱包有问题
1. 切换后没有自动弹出新链的钱包提示连接
2. 需要先断开链接，用户未必知道
3. 第一次切换后，弹出钱包，我没有接受，拒绝关闭了，下次再切换过去就一直不出钱包连接。

这里的逻辑是否可以是
1. 根据默认条件链接默认钱包
2. 如果用户更改了源链，如果跟已连接钱包不同，则进行新的钱包连接
3. 源链和目的链之间的箭头应该可以点击，进行位置对换。

**Comment by 1022ranji** [comment]
源链选择主网时，读取了我的crab 网络地址
![image](https://user-images.githubusercontent.com/80877629/127998705-00cd2ce1-6c65-4afb-8bd3-26bfedae5987.png)

**Comment by 1022ranji** [comment]
点击左侧重置源链网络会出现白屏
![image](https://user-images.githubusercontent.com/80877629/128004401-b42bb65b-68f0-48ac-a19c-a0251841900d.png)
![image](https://user-images.githubusercontent.com/80877629/128004425-e3c77e1d-5f34-4bc4-a197-4030a6cbc287.png)

**Comment by 1022ranji** [comment]
d2e 流程
Pangolin Testnet > Ropsten Testnet , 连接钱包后，当账户余额 > 转账金额+手续费时无法操作，提示余额不足。同时，点选“全部”时，在账户内有余额时仍显示为0。

https://user-images.githubusercontent.com/80877629/128465340-9b3a494b-cd1c-4b4e-92df-ba8a173c1786.mp4

**Comment by 1022ranji** [comment]
e2d （Ropsten > Pangolin）
Kton 转账，余额充足时，输入1的时候，提示“余额不足”，但是输入>1的数时却能正常操作。
![image](https://user-images.githubusercontent.com/80877629/128477098-632364d5-130f-4055-9d55-3abe1b89bc1e.png)
![image](https://user-images.githubusercontent.com/80877629/128477069-f070d66a-4ba9-4143-94e1-a683458af4ec.png)
