### ISSUE TITLE
黑暗模式下顶部栏文字颜色更改

### ISSUE THREAD

**Issue by 1022ranji** [darwinia-network/wormhole-ui#100]
### Importance

General

### Priority

Low

### Description

黑暗模式下将顶部栏文字颜色改为白色。
![image](https://user-images.githubusercontent.com/80877629/133360664-93f07358-e40c-471a-8f4e-e884fea0995f.png)

**Comment by AurevoirXavier** [comment]
中等亮度的蓝色或者白色比较好

背景也提一下亮度
参考 etherscan 或者 github 的黑暗模式，很好的例子
比较舒服的设计都是一些柔和的颜色
