### ISSUE TITLE
Pangolin smart > Pangoro 赎回操作时提示用户将收到 ORING。

### ISSUE THREAD

**Issue by 1022ranji** [darwinia-network/wormhole-ui#125]
### Importance

Serious

### Priority

Medium

### Description

![image](https://user-images.githubusercontent.com/80877629/135752562-a900c767-72e8-456e-b38f-307ebff574c9.png)

**Comment by sxlwar** [comment]
remove prefix directly to keep the logic simple

https://github.com/darwinia-network/wormhole-ui/blob/8d6e356bbd3052d455494b5825ecb53e3813ea6c/src/components/bridge/DVM.tsx#L67-L81
