### ISSUE TITLE
Darwinia > Ethereum | Balance 读取的数值是全部的amount，其中也包含了locked 的 amount，应该把这部分locked的数量去掉。

### ISSUE THREAD

**Issue by 1022ranji** [darwinia-network/wormhole-ui#142]
### Prerequisites

- [X] Can you reproduce the problem in safe mode?
- [X] Are you running the latest version?

### Importance

General

### Priority

High

### Description

![image](https://user-images.githubusercontent.com/80877629/137257434-ea4029a7-752f-4d7d-a138-2caeb97066a7.png)

### How to reproduce this issue

.

### Actual behavior

.

### Expected behavior

.

**Comment by sxlwar** [comment]
@WoeOm 倒是可以，感觉这几个接口有点乱，导致各个应用显示的不一样，或者对于 freeBalance 的定义都不一样

**Comment by WoeOm** [comment]
是指在虫洞做适配，不同网络实现不同获取余额的方法。

**Comment by sxlwar** [comment]
问题是可用余额要不要在各个应用间保持一致？

**Comment by AurevoirXavier** [comment]
> 在哪配置？ 不同方法获取的可用余额应该相同
> 
> 
> 
> 如果按 rpc 的方法，polkadot apps上显示的数据明显不对

我们的锁改过，polkadot apps 的逻辑不适应
