### ISSUE TITLE
staging 环境｜Pangolin-smart > Pangoro 转账报错

### ISSUE THREAD

**Issue by 1022ranji** [darwinia-network/wormhole-ui#169]
### Prerequisites

- [X] Can you reproduce the problem in safe mode?
- [X] Are you running the latest version?

### Importance

General

### Priority

High

### Description

![image](https://user-images.githubusercontent.com/80877629/139232458-ba77b4df-cbef-4b73-8401-c3a7f676459a.png)

Transaction has been reverted by the EVM: { "blockHash": "0x6c73ccedc1102d71314c135f8dd5448ed40077c430fd1bea99c7af13f8aadb1c", "blockNumber": 1098527, "contractAddress": null, "cumulativeGasUsed": 244585, "from": "0xe59261f6d4088bcd69985a3d369ff14cc54ef1e5", "gasUsed": 244585, "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", "status": false, "to": "0xcb48d99a252c0536109385982f4770d96115dca2", "transactionHash": "0xa58843ea80eca49b50ee9e7e542a06a8824eda93783a2fc48336f4ccbae6a30e", "transactionIndex": 0, "events": {} }

### How to reproduce this issue

·

### Actual behavior

·

### Expected behavior

·

**Comment by sxlwar** [comment]
fixed in #170
