### ISSUE TITLE
生产环境中，Pangolin > Ropsten 历史记录中Token名称显示的有问题；将 RING 和 KTON 变为 PRING 和 PKTON

### ISSUE THREAD

**Issue by 1022ranji** [darwinia-network/wormhole-ui#173]
### Importance

General

### Priority

Medium

### Description

![image](https://user-images.githubusercontent.com/80877629/139655705-8b603e94-a042-4b7c-a3ae-53e91eb92076.png)

**Comment by sxlwar** [comment]
fixed in #170
