### ISSUE TITLE
Have to do click network connect before claim in Darwinia Ethereum history records.

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/wormhole-ui#180]
### Prerequisites

- [X] Can you reproduce the problem in safe mode?
- [X] Are you running the latest version?

### Importance

General

### Priority

Medium

### Description

#179 

### How to reproduce this issue

#179 Can not claim 
![image (17)](https://user-images.githubusercontent.com/1070122/140314751-6ebfc91e-330c-4b10-b0ec-b03f894f2d0b.png)

### Actual behavior

pending, metamask does not show up

### Expected behavior

metamask does not show up

**Comment by sxlwar** [comment]
RPC is not healthy, or the Polkadot API initialize failed.
