### ISSUE TITLE
暗黑模式下透明图标着色问题

### ISSUE THREAD

**Issue by MittWillson** [darwinia-network/wormhole-ui#193]
### Prerequisites

- [ ] Can you reproduce the problem in safe mode?
- [X] Are you running the latest version?

### Importance

General

### Priority

Low

### Description

![image](https://user-images.githubusercontent.com/10653144/142590080-ff685131-469c-4636-9abc-9e86ba6b4f73.png)

### How to reproduce this issue

Transfer records page

### Actual behavior

图标显示异常，图标中的结构在暗黑模式下没有着色

### Expected behavior

应该和亮色模式下一样显示效果

**Comment by 1022ranji** [comment]
done
