### ISSUE TITLE
Ethereum  > Darwinia  |  KTON 小数点有 bug

### ISSUE THREAD

**Issue by 1022ranji** [darwinia-network/wormhole-ui#200]
### Prerequisites

- [X] Can you reproduce the problem in safe mode?
- [X] Are you running the latest version?

### Importance

General

### Priority

Medium

### Description

![image](https://user-images.githubusercontent.com/80877629/142959832-5fec3fdf-ed3d-4700-a49c-f41ef54a414f.png)
KTON 单位只能用 int
用了 int 后，小数点单位差 18 位
https://etherscan.io/tx/0x7c7d5d441ebb3670059278f5be84e2be3a18e311b804998bf216ca2fd68e9738

### How to reproduce this issue

·

### Actual behavior

·

### Expected behavior

·

**Comment by HackFisher** [comment]
@WoeOm Any suggestion? We should use big number for blockchain applications? Precise calculation

**Comment by WoeOm** [comment]
处理用户输入值使用： https://mikemcl.github.io/bignumber.js/
或者 @ethersproject/bignumber： https://docs.ethers.io/v5/api/utils/display-logic/

如果其他接口需要提供 BN.js 类型，可以再做一次转化， BigNumberToBn, EthersBNToBn 。
