### ISSUE TITLE
Pangoro > Pangolin-smart 历史记录  | 无法识别 Pangoro 网络地址

### ISSUE THREAD

**Issue by 1022ranji** [darwinia-network/wormhole-ui#210]
### Prerequisites

- [X] Are you running the latest version?

### Importance

General

### Priority

High

### Description

![image](https://user-images.githubusercontent.com/80877629/144223617-428cf4b7-4085-4e62-87d2-33d3d1a99738.png)
![image](https://user-images.githubusercontent.com/80877629/144223437-847ec779-9b85-4269-bd40-2f73789b6c1b.png)

### How to reproduce this issue

·

### Actual behavior

·

### Expected behavior

·

**Comment by 1022ranji** [comment]
Pangolin-smart > Pangoro ｜填写表单时，同样出现填写正确的pangoro地址时被提醒错误。
![image](https://user-images.githubusercontent.com/80877629/144224354-845c8995-7d30-44e4-a2fb-eb35892bfd8a.png)

**Comment by sxlwar** [comment]
重置后 pangolin 和 pangoro 的ss58Prefix 变了。 #208

**Comment by 1022ranji** [comment]
ok
