### ISSUE TITLE
querying 时间过长，无法进行下一步转账操作

### ISSUE THREAD

**Issue by 1022ranji** [darwinia-network/wormhole-ui#243]
### Importance

General

### Priority

High

### Description

![image](https://user-images.githubusercontent.com/80877629/146865837-7fd06652-ebb3-40d3-8d32-19118e908515.png)

**Comment by 1022ranji** [comment]
RPC 经常断开，当前是从插件中查询的，是否可以走特定的RPC

**Comment by xiaoch05** [comment]
> RPC 经常断开，当前是从插件中查询的，是否可以走特定的RPC cc @xiaoch05

是否是因为ws的原因？如果用http来请求呢 @sxlwar

**Comment by sxlwar** [comment]
> > RPC 经常断开，当前是从插件中查询的，是否可以走特定的RPC cc @xiaoch05
> 
> 是否是因为ws的原因？如果用http来请求呢 @sxlwar

对，http 会好点，不用担心 rpc 状态，但是出错后结果是一样的。我觉得最有效的办法是重试

**Comment by 1022ranji** [comment]
重试是指？用户手动刷新吗

**Comment by 1022ranji** [comment]
done
