### ISSUE TITLE
Tip feature improvement

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/wormhole-ui#256]
![image](https://user-images.githubusercontent.com/80877629/147541890-c8892496-c136-4e0d-9cc2-0c900c1b6c34.png)
这里少个提示 #254

_Originally posted by @1022ranji in https://github.com/darwinia-network/wormhole-ui/issues/255#issuecomment-1001920511_

**Comment by sxlwar** [comment]
that's the problem of crab-subquery, forgot to sync to production
