### ISSUE TITLE
空投模块：必须成功连接Tron后才能进入表单页

### ISSUE THREAD

**Issue by 1022ranji** [darwinia-network/wormhole-ui#52]
情况描述：点击“Connect To Tron”后没有判断用户是否有Tron的钱包，或者是否处于lock的状态，直接进入了表单页，并且在“Connect To Tron”一栏显示了“false”。
修改：
1. 点击“Connect To Tron”后判断用户是否有Tron的钱包，当没有钱包时在右上角弹出提示“Please install Tronlink first.”(请先安装Tronlink)
2. 当用户有Tronlink但是处于lock的状态时，提示“Please unlock Tronlink first.”(请解锁Tronlink)
![image](https://user-images.githubusercontent.com/80877629/132155704-d82a20dc-9005-43e6-9e7d-266c552851da.png)
![image](https://user-images.githubusercontent.com/80877629/132155727-05fa4674-77f4-441f-a573-2d6bfc1a8a85.png)

**Comment by sxlwar** [comment]
why？
历史记录那块不是已经单独入口了，这个地方为什么又要耦合起来？

https://github.com/darwinia-network/wormhole-ui/blob/908408de396aa5dea3d0a7d28098f18954e5c250/src/utils/network/connection.tsx#L220

![image](https://user-images.githubusercontent.com/20088392/132293542-e1b49ff0-8127-49df-a770-d33415abf67a.png)

**Comment by 1022ranji** [comment]
这个issue不是指空投记录页面，是下边空投点击去的页面。
