### ISSUE TITLE
历史记录模块中将“已确认”的交易从“进行中”分离出来

### ISSUE THREAD

**Issue by 1022ranji** [darwinia-network/wormhole-ui#55]
![image](https://user-images.githubusercontent.com/80877629/132182626-8ce138f6-7a8c-4d1f-b555-3d0dc0e66e4f.png)

**Comment by sxlwar** [comment]
这个图想说明什么？
测试好几遍都查不到混合结果
如果是 claim 之后的变绿的，刷新页面

**Comment by 1022ranji** [comment]
不是claim之后变绿的，输入地址之后查询出来的就是这样的，其中三个交易中已经有两个是完成的了，没有进入“已确认”页面，刷新之后仍然是一样的状态。
是不是我们测的不是一个地址，我查的是Darwinia 主网地址，不是测试网的。

**Comment by sxlwar** [comment]
https://api.darwinia.network/api/ethereumBacking/locks?address=0xf05ddab8a7bd3c3c6b3b8d3f3bdee08b4c3bae35045bd196980ec6d1caeb2522&confirmed=false&row=10&page=0 @xiaoch05 看 下这个请求， confiremed 查询参数是 fasle，接口上返回的结果逻辑上 confirmed 是ture

**Comment by xiaoch05** [comment]
> https://api.darwinia.network/api/ethereumBacking/locks?address=0xf05ddab8a7bd3c3c6b3b8d3f3bdee08b4c3bae35045bd196980ec6d1caeb2522&confirmed=false&row=10&page=0 @xiaoch05 看 下这个请求， confiremed 查询参数是 fasle，接口上返回的结果逻辑上 confirmed 是ture

现在后端主网部署的和测试网不是同一个分支
目前这个功能只在测试网上能提现，代码还没有merge到主网部署的分支

**Comment by 1022ranji** [comment]
这个代码merge到主网部署的分支能够在明天或者下周一上线之前完成吗？

**Comment by xiaoch05** [comment]
> 这个代码merge到主网部署的分支能够在明天或者下周一上线之前完成吗？

等下我单独提个pr吧

**Comment by 1022ranji** [comment]
> > 这个代码merge到主网部署的分支能够在明天或者下周一上线之前完成吗？
> 
> 等下我单独提个pr吧

好的。
