### ISSUE TITLE
无法查看ethereum 地址的跨链历史交易记录。

### ISSUE THREAD

**Issue by 1022ranji** [darwinia-network/wormhole-ui#56]
![image](https://user-images.githubusercontent.com/80877629/132187006-971ef5b5-8c87-4640-b44d-7d4781634115.png)

**Comment by sxlwar** [comment]
![image](https://user-images.githubusercontent.com/20088392/132291834-5e39a966-a628-4d28-b743-76f8d01e3489.png)
测试是过的，你的截图上显示查回来 0 条

**Comment by 1022ranji** [comment]
你上图中查询的是Ropsten，我查的是在Ethereum上，老虫洞是能查出跨链记录的，目前在新虫洞上查不到。
![image](https://user-images.githubusercontent.com/80877629/132296494-92b3020e-5041-48d6-88ed-3f2f7bb8a69f.png)

**Comment by sxlwar** [comment]
worked.

other problem duplicated with #55
