### ISSUE TITLE
Remove "Tron" from the "Transfer Records"

### ISSUE THREAD

**Issue by 1022ranji** [darwinia-network/wormhole-ui#63]
### Importance

General

### Priority

Medium

### Description
![image](https://user-images.githubusercontent.com/80877629/132451920-0c57c4db-952a-4a3b-abbf-ee0bcf39b74c.png)

@sxlwar 这边基础测试完成了，出现的可优化的地方已提在了issue中。

**Comment by 1022ranji** [comment]
@sxlwar  这个issue下周一上线前需要处理一下。

**Comment by sxlwar** [comment]
为什么删？

**Comment by 1022ranji** [comment]
Tron这个网络下没有跨链转账，所以也查询不到跨链记录；Tron这个网络下只能查询到空投记录。

**Comment by 1022ranji** [comment]
Tron这个网络下没有跨链转账，所以也查询不到跨链记录；Tron这个网络下只能查询到空投记录。
