### ISSUE TITLE
UI 上的一些意见

### ISSUE THREAD

**Issue by DreUncle** [darwinia-network/wormhole-ui#65]
### Importance

General

### Priority

Medium

### Description

![image](https://user-images.githubusercontent.com/34929683/132470745-7b75cb7c-7ebc-4e35-a6f0-a13c8b6f2739.png)
![image](https://user-images.githubusercontent.com/34929683/132470872-6b687197-1cbd-4b7e-97dc-019527ae08e0.png)
favicon 换成和dvm一样的圆形的

![image](https://user-images.githubusercontent.com/34929683/132470946-78855575-6d50-48d7-9549-d180c4ad995d.png)
黑暗模式下把顶部和底部的背景色块去掉

![image](https://user-images.githubusercontent.com/34929683/132471056-a347cf13-0c5d-43c3-bbc2-de57673bd042.png)
白天模式下不要紫色的色块，背景和文字的颜色和做法统一成dvm那样（大体上是希望各个地方都尽量统一，这样以后管理和修改起来比较方便）

![image](https://user-images.githubusercontent.com/34929683/132471287-8aec0b12-a1b0-4736-a7a5-ee2eb0b27861.png)
这个an按钮，如果可以的话改成反色的，紫色底，白色的箭头

![image](https://user-images.githubusercontent.com/34929683/132471784-af5ad76c-376f-4c62-94ea-a7269198c9d1.png)
底部白色卡片复制一下dvm的css过来，统一起来，虫洞这边显得阴影太重了

![image](https://user-images.githubusercontent.com/34929683/132471904-0964ecc5-3ba3-48bb-ba98-5c82b1a5dd82.png)
这个建议还是改成黑字和暗黑模式下白字

![image](https://user-images.githubusercontent.com/34929683/132472712-9654ab72-6fd7-4fd0-8aca-13fbb89a3af2.png)
将logo 的 height 改为 2rem，放大一些

**Comment by sxlwar** [comment]
顶部导航和底部 footer 不能省，尽管看起来逼格会高点，但会在小屏，滚动，吸顶等情况下使用页面看起来很乱

commit 0dfb59c8a569cf8 的前一个就是透明背景

smart app 最好也采用 header body footer 三段布局，不过现在问题不大，因为内容简单，还没有路由

手续费文字是有状态的，所以区分颜色，有过渡动画
