### ISSUE TITLE
Darwinia > Ethereum 转账数量为Max时的提示

### ISSUE THREAD

**Issue by 1022ranji** [darwinia-network/wormhole-ui#94]
### Importance

General

### Priority

Medium

### Description

情况描述：从Darwinia> Ethereum 时，在点击“Max”之后没办法转账，是由于除了跨链费用外还会有一定的交易费用，这个交易费用通常是变动的。从其他网络转回Darwinia不会出现这个问题。
改动方式：之前的提示不太明显，可以将其替换为“You need to set aside a little fee to pay a transaction fee in addition to a cross-chain fee.❓”然后鼠标移动到❓会出现悬浮提示“The transaction fee is dynamic.” 如下图所示：
![image](https://user-images.githubusercontent.com/80877629/133254454-4805048a-6219-4c6d-9296-9f4c25d1de3d.png)

**Comment by sxlwar** [comment]
本来就是动态的
